CREATE TABLE [dbo].[ForecastParameter] (
    [company_code]                  VARCHAR (3)    NOT NULL,
    [customer_number]               VARCHAR (10)   NOT NULL,
    [item_number]                   VARCHAR (11)   NOT NULL,
    [store_count_existing]          INT            NULL,
    [store_count_new]               INT            NULL,
    [initial_qty_per_new_store]     DECIMAL (7, 2) NULL,
    [pipeline_start]                VARCHAR (4)    NULL,
    [pipeline_end]                  VARCHAR (4)    NULL,
    [projected_sales_rate_existing] DECIMAL (5, 2) NULL,
    [projected_sales_rate_new]      DECIMAL (5, 2) NULL,
    [one_time_item_flag]            BIT            NULL,
    [pl_pct_py_01]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_02]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_03]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_04]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_05]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_06]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_07]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_08]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_09]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_10]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_11]                  DECIMAL (5, 2) NULL,
    [pl_pct_py_12]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_01]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_02]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_03]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_04]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_05]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_06]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_07]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_08]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_09]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_10]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_11]                  DECIMAL (5, 2) NULL,
    [pl_pct_cy_12]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_01]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_02]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_03]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_04]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_05]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_06]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_07]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_08]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_09]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_10]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_11]                  DECIMAL (5, 2) NULL,
    [pl_pct_ny_12]                  DECIMAL (5, 2) NULL,
    [timestamp]                     TIMESTAMP      NOT NULL
);

