CREATE TABLE [dbo].[ForecastParameterBcp] (
    [CO_CODE]                       NVARCHAR (255) NULL,
    [CUSTOMER_NUMBER]               NVARCHAR (255) NULL,
    [ITEM_NUMBER]                   NVARCHAR (255) NULL,
    [STORE_COUNT_EXISTING]          FLOAT          NULL,
    [STORE_COUNT_NEW]               FLOAT          NULL,
    [INITIAL_QTY_PER_NEW_STORE]     FLOAT          NULL,
    [PIPELINE_START]                NVARCHAR (255) NULL,
    [PIPELINE_END]                  NVARCHAR (255) NULL,
    [PROJECTED_SALES_RATE_EXISTING] FLOAT          NULL,
    [PROJECTED_SALES_RATE_NEW]      FLOAT          NULL,
    [MANUAL_FC_MODE]                NVARCHAR (255) NULL,
    [CALC_PARTIAL_SR]               NVARCHAR (255) NULL,
    [PL_PCT_PY_01]                  FLOAT          NULL,
    [PL_PCT_PY_02]                  FLOAT          NULL,
    [PL_PCT_PY_03]                  FLOAT          NULL,
    [PL_PCT_PY_04]                  FLOAT          NULL,
    [PL_PCT_PY_05]                  FLOAT          NULL,
    [PL_PCT_PY_06]                  FLOAT          NULL,
    [PL_PCT_PY_07]                  FLOAT          NULL,
    [PL_PCT_PY_08]                  FLOAT          NULL,
    [PL_PCT_PY_09]                  FLOAT          NULL,
    [PL_PCT_PY_10]                  FLOAT          NULL,
    [PL_PCT_PY_11]                  FLOAT          NULL,
    [PL_PCT_PY_12]                  FLOAT          NULL,
    [PL_PCT_CY_01]                  FLOAT          NULL,
    [PL_PCT_CY_02]                  FLOAT          NULL,
    [PL_PCT_CY_03]                  FLOAT          NULL,
    [PL_PCT_CY_04]                  FLOAT          NULL,
    [PL_PCT_CY_05]                  FLOAT          NULL,
    [PL_PCT_CY_06]                  FLOAT          NULL,
    [PL_PCT_CY_07]                  FLOAT          NULL,
    [PL_PCT_CY_08]                  FLOAT          NULL,
    [PL_PCT_CY_09]                  FLOAT          NULL,
    [PL_PCT_CY_10]                  FLOAT          NULL,
    [PL_PCT_CY_11]                  FLOAT          NULL,
    [PL_PCT_CY_12]                  FLOAT          NULL,
    [PL_PCT_NY_01]                  FLOAT          NULL,
    [PL_PCT_NY_02]                  FLOAT          NULL,
    [PL_PCT_NY_03]                  FLOAT          NULL,
    [PL_PCT_NY_04]                  FLOAT          NULL,
    [PL_PCT_NY_05]                  FLOAT          NULL,
    [PL_PCT_NY_06]                  FLOAT          NULL,
    [PL_PCT_NY_07]                  FLOAT          NULL,
    [PL_PCT_NY_08]                  FLOAT          NULL,
    [PL_PCT_NY_09]                  FLOAT          NULL,
    [PL_PCT_NY_10]                  FLOAT          NULL,
    [PL_PCT_NY_11]                  FLOAT          NULL,
    [PL_PCT_NY_12]                  FLOAT          NULL
);

