CREATE TABLE [dbo].[Forecast2008_09Bcp] (
    [COMPANY_CODE]     NVARCHAR (255) NULL,
    [ITEM_NUMBER]      NVARCHAR (255) NULL,
    [BILL_TO_CUSTOMER] NVARCHAR (255) NULL,
    [FORECAST_METHOD]  NVARCHAR (255) NULL,
    [CURRENT_01]       FLOAT          NULL,
    [CURRENT_02]       FLOAT          NULL,
    [CURRENT_03]       FLOAT          NULL,
    [CURRENT_04]       FLOAT          NULL,
    [CURRENT_05]       FLOAT          NULL,
    [CURRENT_06]       FLOAT          NULL,
    [CURRENT_07]       FLOAT          NULL,
    [CURRENT_08]       FLOAT          NULL,
    [CURRENT_09]       FLOAT          NULL,
    [CURRENT_10]       FLOAT          NULL,
    [CURRENT_11]       FLOAT          NULL,
    [CURRENT_12]       FLOAT          NULL,
    [NEW_01]           FLOAT          NULL,
    [NEW_02]           FLOAT          NULL,
    [NEW_03]           FLOAT          NULL,
    [NEW_04]           FLOAT          NULL,
    [NEW_05]           FLOAT          NULL,
    [NEW_06]           FLOAT          NULL,
    [NEW_07]           FLOAT          NULL,
    [NEW_08]           FLOAT          NULL,
    [NEW_09]           FLOAT          NULL,
    [NEW_10]           FLOAT          NULL,
    [NEW_11]           FLOAT          NULL,
    [NEW_12]           FLOAT          NULL
);

