CREATE TABLE [dbo].[ItemCategoryBcp] (
    [ITEM]                NVARCHAR (255) NULL,
    [ITEM_DESCRIPTION]    NVARCHAR (255) NULL,
    [ITEM_CATEGORY]       NVARCHAR (255) NULL,
    [BRAND]               NVARCHAR (255) NULL,
    [BRAND_DESC]          NVARCHAR (255) NULL,
    [PREFIX]              NVARCHAR (255) NULL,
    [PRODUCT_PREFIX_DESC] NVARCHAR (255) NULL,
    [PRODUCT_CATEGORY]    NVARCHAR (255) NULL,
    [PROD_CATEGORY_DESC]  NVARCHAR (255) NULL
);

