CREATE TABLE [dbo].[POSXlsBcp] (
    [F1] NVARCHAR (255) NULL,
    [F2] NVARCHAR (255) NULL,
    [F3] NVARCHAR (255) NULL,
    [F4] NVARCHAR (255) NULL,
    [F5] FLOAT          NULL,
    [F6] NVARCHAR (255) NULL
);

