ALTER TABLE [dbo].[CompanyOrganization]
    ADD CONSTRAINT [PK_CompanyOrganzation] PRIMARY KEY CLUSTERED ([company_code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

