ALTER TABLE [dbo].[Item]
    ADD CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED ([item_number] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

