ALTER TABLE [dbo].[WeekCalendar]
    ADD CONSTRAINT [PK_WeekCalendar] PRIMARY KEY CLUSTERED ([week_end_date] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

